source 'https://rubygems.org'

ruby '2.2.0'
gem 'rails', '4.2.3'
gem 'pg'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'certified'
gem 'dotenv-rails', require: 'dotenv/rails-now'
gem 'devise'
gem 'omniauth'
gem 'omniauth-google-oauth2'
# gem 'googleauth'
gem 'google-api-client', require: 'google/api_client'
# gem 'google_contacts_api'
gem 'omnicontacts'
gem 'rest-client'
gem 'nokogiri'
gem 'carrierwave'

group :development, :test do
  gem 'byebug'
  gem 'pry-rails'
  gem 'pry-coolline'
  gem 'awesome_print'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'sextant'
  gem 'faker'
  gem 'better_errors'
end
