# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57fb8d55af270fd34634bbdd6c75df7944d6d65b826bfa897ad016e9e0d88c6de81d33f3e7ed08529b7fd5b3ec9fe52d4e7027e2a9ec8b8337bcd1a0af566a54

test:
  secret_key_base: a828ee4a4a602e4be699146dcd3911442270cbdc650eafaea6a89cdb8bbda6c33e6f2c983ab50e164b182f69919ffdb3a705798f0ea477d40edc90a142d92428

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
